'''This submodule defines signals that interact with electronic devices.
'''
from ..signals import Data, Control

import numpy as np


class Voltage(Control):
    '''A signal class representing a voltage generated by an electronic device.
    '''
    def __init__(self, signals: np.ndarray, shape: tuple[int, int] = None) -> None:
        super().__init__(signals, shape)


class Current(Control):
    '''A signal class representing a current generated by an electronic device.
    '''
    def __init__(self, signals: np.ndarray, shape: tuple[int, int] = None) -> None:
        super().__init__(signals, shape)
